export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const GET_KEYBOARDS = 'GET_KEYBOARDS'

export const SIGNUP = 'SIGNUP'

export const POST_KEYBOARD = 'POST_KEYBOARD'

export const PREVIEW_KEYBOARD = 'PREVIEW_KEYBOARD'

export const SHOW_PREVIEW_KEYBOARD = 'SHOW_PREVIEW_KEYBOARD'